#!/bin/bash

set -e

if [ "$UID" != "0" ]; then
	echo "Must be run as root... "
	sudo $0 "$@"
	exit
fi

# allow many files
ulimit -Hn 1000000 && ulimit -n 1000000

ROOT_DIR=/home/genode/tiotest
DATA_DIR=$ROOT_DIR/data
TEST_DIR=$ROOT_DIR/scratch

TIOTEST=$ROOT_DIR/tiobench.git/tiotest

mkdir -p $DATA_DIR
mkdir -p $TEST_DIR

VMM=$(dmidecode --dump | grep -q vboxVer_5 && echo vbox5 || echo vbox6)
NPROC=cpu$(nproc)

DESC="$VMM-$NPROC-$(date '+%F-%H-%M')"
CMD="$TIOTEST -d $TEST_DIR $@"

(
	echo "$DESC: $CMD"
	echo 
	time $CMD
	cat /proc/loadavg
) |& tee $DATA_DIR/$DESC
